### ISSUE TITLE
consider a guide to using bower as alternative

### ISSUE THREAD

**Issue by cornernote** [cebe/assetfree-yii2#2]
Thanks for this repo! Great idea, I hate the fxp plugin because it always seems to bug when composer updates, and its also very slow.

Do you use bower instead?  Are you able to give a quick-start guide to using bower to get the required assets, (including making sure they go into the right folders)?

**Comment by cebe** [comment]
That is not the purpose of this package, I neither hate the fxp plugin nor am I using an alternative.
This package is used to avoid installation of bower packages when yii2 is used for API and backend stuff where no frontend packages are needed.
