### ISSUE TITLE
You break the compatibility of fxp/composer-asset-plugin

### ISSUE THREAD

**Issue by francoispluchino** [cebe/assetfree-yii2#4]
@cebe,

First of all, thank you for your support of the Composer plugin [Fxp Composer Asset Plugin](https://github.com/fxpio/composer-asset-plugin).

But with your workaround on Packagist using the `provide`, you break the compatibility of the plugin.

Indeed, Composer first check packages on Packagist, and uses the VCS Repositories after. Now that you reference packages under the virtual vendor `bower-asset` in Packagist, Composer considers that the package exists on Packagist.

Please remove your Packagist references.

For more details, see fxpio/composer-asset-plugin#268 and #1.

Best regards

**Comment by cebe** [comment]
@francoispluchino I see the problem but why does it only appear today? This package exists on packagist for over 9 month now.

**Comment by cebe** [comment]
seems unlrelated to this package.
