### ISSUE TITLE
2.0.13 does not prevent bower-asset/inputmask installation

### ISSUE THREAD

**Issue by comradefuzz** [cebe/assetfree-yii2#5]
```
$ composer why bower-asset/inputmask
yiisoft/yii2  2.0.13  requires  bower-asset/inputmask (~3.2.2 | ~3.3.5)
```

**Comment by cebe** [comment]
how does your composer.json look like?

**Comment by comradefuzz** [comment]
That's my require block
```
"require": {
        "php": ">=5.4.0",
        "cebe/assetfree-yii2": "=2.0.13",
        "yiisoft/yii2": "=2.0.13",
        "vlucas/phpdotenv": "^2.4",
        "symfony/process": "^3.0",
        "yiisoft/yii2-queue": "^2.0"
    },
```

**Comment by cebe** [comment]
Oh now I see, the package name changed from `bower-asset/jquery.inputmask` to `bower-asset/inputmask`

**Comment by cebe** [comment]
should be fixed by adding the package: https://github.com/cebe/assetfree-yii2/commit/2e60a9ebdbd642a8bdbab876eae996a613f816b2 I have recreated the 2.0.13 tag for that commit.

Thanks for reporting!

**Comment by cebe** [comment]
> "yiisoft/yii2": "=2.0.13",

btw, there is Yii 2.0.13.1, which fixes a few regressions.
